server:
  port: 9002

spring:
  application:
    name: order-services

  datasource:
    url: jdbc:mysql://localhost:3306/college
    driver-class-name: com.mysql.cj.jdbc.Driver
    username: root
    password: Pass

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    database-platform: org.hibernate.dialect.MySQL8Dialect

management:
  endpoints:
    web:
      exposure:
        include: health,info
service:
  user: http://user-service:9001
  product: http://product-service:9003

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui.html